; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = foc_openloop

[env]                          ; inherited by all envs
platform = ststm32
board = nucleo_f446re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
monitor_eol = LF
monitor_echo = yes
build_flags = -D HAL_TIM_MODULE_ENABLED
lib_deps =
    askuric/Simple FOC@^2.3.4
lib_archive = false

[env:encoders_only]
build_src_filter = -<*> +<common/> +<apps/encoders_only/>
build_flags = ${env.build_flags} -D APP_NAME=encoders_only

[env:foc_openloop]
build_src_filter = -<*> +<common/> +<apps/foc_openloop/>
build_flags = ${env.build_flags} -D APP_NAME=foc_openloop

[env:foc_closedloop]
build_src_filter = -<*> +<common/> +<apps/foc_closedloop/>
build_flags = ${env.build_flags} -D APP_NAME=foc_closedloop